/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.javalin.Javalin;
//import io.javalin.http.staticfiles.Location;

public class App {
    public void runServer() {
        var app = Javalin.create(config -> {
            config.routes.get("/", ctx -> ctx.result("Hello World"));
        }).start(7070);
    }

    public static void main(String[] args) {
        new App().runServer();
    }
}
